#!/bin/sh
# Rebuild test/RUN_local.lua: the edited source wrapped as a local module,
# followed by the showcase demo (its loadstring line stripped).
# Run from the repo root: sh tools/build_runlocal.sh
set -e
out=test/RUN_local.lua
{
	echo "-- NEMESIS local test build (edited source + showcase demo, self-contained)"
	echo "-- Run THIS in your executor. No GitHub fetch, uses the local edited source."
	echo "-- Generated by tools/build_runlocal.sh, do not edit by hand."
	echo ""
	echo "local NEMESIS = (function()"
	cat source.lua
	echo ""
	echo "end)()"
	echo ""
	grep -v '^local NEMESIS = loadstring' showcase.lua
} > "$out"
echo "built $out"
